### ISSUE TITLE
não consigo installar usando o pip

### ISSUE THREAD

**Issue by pretinhodev** [tbrugz/geodata-br#5]
tentei adicionar ao meu notebook no kaggle, mas isso acontece...
![image](https://user-images.githubusercontent.com/38338362/86857312-a4c09a00-c094-11ea-9fc5-e5520585d9e1.png)

**Comment by tbrugz** [comment]
Olá, este projeto contém arquivos geojson para municipios brasileiros - não é um projeto python. Devem haver bibliotecas python que podem carregar arquivos geojson, porém eu não saberia indicar nenhuma
