### ISSUE TITLE
License / Licença

### ISSUE THREAD

**Issue by pedropaulosuzuki** [tbrugz/geodata-br#6]
Hello! It would be nice to have a license added to this github repo, even more so if it is an Open Source License, such as the MIT, Unlicense or the GNU General Public License. Thanks!

Boa tarde! Seria interessante adicionar uma licença a esse repositório. Se possível utilizar uma licença de código aberto, como a licença MIT, a Unlicense ou a GNU GPL, melhor ainda! Muito obrigado!

**Comment by tbrugz** [comment]
Olá @pedropaulosuzuki, obrigado pela dica, faz sentido sim. Considerando que os dados vêm do IBGE, estou pensando em utilizar a CC0 (https://choosealicense.com/licenses/cc0-1.0/) para ficar o mais "domínio público" possível. Alguma consideração?

**Comment by tbrugz** [comment]
Licença CC0 adotada!
